import os 
import numpy as np 
import pandas as pd 
from SR.spectral_residual import Silency


if __name__=="__main__":
    file_path = './data/series24.csv'
    save_path = './data/series24_sr.csv'

    df = pd.read_csv(file_path)
    timestamp = df["timestamp"].values 
    value = df["value"].values  

    spec = Silency(amp_window_size=3, series_window_size=3, score_window_size=5)
    sr = spec.transform_spectral_residual(value)
    threshold = np.percentile(sr, 97.5)
    # pred represents the label generated by employing the SR algorithm
    pred = np.array([1.0 if sr[i] > threshold else 0.0 for i in range(0, len(sr))])

    df.loc[:,"pred"] = pred
    df1 = df[df.label<2.0] # remove missing values
    df1.to_csv(save_path, index=None)
